// Custom server file for Plesk Node.js (Phusion Passenger)
// This file simply delegates execution to the Next.js standalone server.

const path = require('path');

// When Next.js builds in standalone mode, it places the server in `.next/standalone`
const nextStandaloneServerPath = path.join(__dirname, '.next', 'standalone', 'server.js');

try {
  console.log('Starting Next.js via Plesk Passenger...');
  // Require the actual Next.js server generated by the standalone build
  require(nextStandaloneServerPath);
} catch (error) {
  console.error('Failed to start Next.js application.');
  console.error('Ensure that you have run "npm run build" and that the "output: standalone" setting is in next.config.js');
  console.error(error);
  process.exit(1);
}
